
services:
  
  redis:
    image: redis:latest
    container_name: redis_cache
    command: redis-server --requirepass 123456
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network


volumes:
  redis_data:

networks:
  app_network:
    driver: bridge