services:
  e-commerce-management-db:
    image: postgres:15-alpine
    container_name: e-commerce-management-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: test
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes: 
      - pgdata:/var/lib/postgresql/data
   
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


  
  redis:
    image: redis:8.0-alpine
    container_name: redis-cache
    
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
    # healthcheck:
    #   test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-your_secure_redis_password}", "ping"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - PORT=8000
      - DB_HOST=e-commerce-management-db
      - DB_PORT=5432
      - DB_NAME=test
      - DB_USERNAME=postgres
      - DB_PASSWORD=12345
      - DB_SYNC=true
      - DB_LOGGING=true
      - REDIS_URL=redis://192.168.2.100:6379
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET:-your_access_token_secret}
      - JWT_ACCESS_EXPIRATION_TIME=${JWT_ACCESS_EXPIRATION_TIME:-15m}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET:-your_refresh_token_secret}
      - JWT_REFRESH_EXPIRATION_TIME=${JWT_REFRESH_EXPIRATION_TIME:-7d}
      - THROTTLE_TTL=${RATE_LIMIT_TTL:-6000}
      - THROTTLE_LIMIT=${RATE_LIMIT_MAX:-100}
    depends_on:
        redis:
          condition: service_healthy
        e-commerce-management-db:
          condition: service_healthy
    networks:
      - app-network
    volumes:
      - .:/app
      - /app/node_modules      
volumes:
   pgdata:
    name: e-commerce-management-system-pgdata
    driver: local
   redis-data:
    name: e-commerce-management-system-redis-data
    driver: local

networks: 
    app-network:
      driver: bridge   